# Implementación Práctica de Numpy

En este apartado desarrollaremos ciertos ejercicios que demuestran la utilidad de Numpy, entre los cuales están:

- Manipulación de Arreglos y Matrices
- Pruebas de eficiencia en tiempo de ejecución
- Algunas funciones estadísticas
- Mascaras Booleanas
- Indexing avanzado

¡Empecemos!

## Operaciones Con Arreglos y matrices

El algebra lineal es una rama de suma importancia en la IA, ya que es el fundamento del manejo de matrices ( ¡Y en IA todo son matrices!)

Por lo que podemos empezar a probar las funcionalidades de numpy con ello, por ejemplo, supongamos que tenemos el siguiente sistema de ecuaciones:

$$
\begin{aligned}
2 x+3 y-z & =5 \\
4 x-y+2 z & =6 \\
-2 x+7 y+3 z & =8
\end{aligned}
$$

Luego, para hallar el vector, $v=[x, y, z]$, que soluciona dicho sistema seguiriamos los siguientes pasos...




Paso 1: Recordemos que este sistema podemos representarlo en forma matricial:

$$
A=\left(\begin{array}{ccc}
2 & 3 & -1 \\
4 & -1 & 2 \\
-2 & 7 & 3
\end{array}\right), \quad b=\left(\begin{array}{l}
5 \\
6 \\
8
\end{array}\right)
$$



Paso 2: Luego de esto lo pasamos a su forma aumentada $[A \mid b]$

$$
[A \mid b]=\left(\begin{array}{ccc|c}
2 & 3 & -1 & 5 \\
4 & -1 & 2 & 6 \\
-2 & 7 & 3 & 8
\end{array}\right)
$$


Paso 3: Y que resolviendo por el método de preferencia nos debería quedar de la siguiente manera

$$
[I \mid v]=\left(\begin{array}{ccc|c}
1 & 0 & 0 & 47/36 \\
0 & 1 & 0 & 10/9 \\
0 & 0 & 1 & 17/18
\end{array}\right)
$$

Bueno pero ¿y cómo se ve todo esto numpy?

(array([[ 2,  3, -1],
        [ 4, -1,  2],
        [-2,  7,  3]]),
 [5, 6, 8])

array([1.30555556, 1.11111111, 0.94444444])

array([5., 6., 8.])

### Caso de uso
¿Y de qué nos sirve saber resolver sistemas de ecuaciones en las ciencias de los datos?

Suponga que tenemos una cantidad de observaciones de un fenómeno, por ejemplo, el valor de la vivienda en una ciudad,
y que además tenemos información sobre cada vivienda (Ubicación, Nro de Habitaciones, Nro de Baños, Metros cuadrados, etc.).
Ahora, si estudiamos los datos ¿Podríamos predecir el precio de una casa de la que no den dicha información?

La respuesta es sí, este es un ejemplo sencillo de Regresión Lineal Múltiple, y se resuelve utilizando operaciones Matriciales
como las que acabamos de ver.

NameError: name 'x1_1' is not defined

### Estadísticas de matrices
Probemos ahora las funciones estadísticas...
Para comenzar creemos una matriz cuadrada de tamaño n, llena de numeros aleatorios del 0 al 100

(5000, 5000)

#### Recordemos algunas definciones de estadística
La distribución uniforme continua en el intervalo $[a,b]$ tiene la siguiente función de densidad de probabilidad:
$$
f(x; a, b) = \begin{cases}
\frac{1}{b-a} & \text{para } a \leq x \leq b, \\
0 & \text{para los demás casos.}
\end{cases}
$$
La siguiente 'Media'
$$
E[X] = \frac{a + b}{2}
$$
... y la siguiente varianza
$$
\text{Var}(X) = \frac{(b - a)^2}{12}
$$


Como resultado, para nuestra Uniforme, en el intervalo $[0,100]$ tendriamos lo siguiente
Media
$$
E[X] = \frac{0 + 100}{2} = 50
$$
... y la siguiente varianza
$$
\text{Var}(X) = \frac{(100 - 0)^2}{12} = 833.33
$$

Media: 49.4942472
Mediana: 49.0
Varianza: 833.2889417852939


Tiempo de ejecucion lenguale nativo media 4.2224215999999615
Tiempo de ejecucion lenguale nativo media 14.029779800000142
Tiempo de ejecucion lenguale nativo media 0.019032199999855948
Tiempo de ejecucion lenguale nativo media 0.11360239999976329


### Finalmente ...
¿Podriamos etiquetar datos por medio de numpy?
Supongamos que queremos leer los datos de este archivo

array([[  18.,   12.,  -10.,  -11.,  -18.],
       [ -55.,   49.,  -27.,   -9.,  -57.],
       [ -13.,   36.,   13.,  -79.,   72.],
       [  -3.,    5.,  -26.,   15.,  -88.],
       [  -1.,  -18., -100.,   68.,  -31.],
       [  17.,  -15.,  -78.,   41.,   55.],
       [  nan,   nan,   nan,   nan,   nan],
       [  nan,   nan,   nan,   nan,   nan],
       [  nan,   nan,   nan,   nan,   nan],
       [  nan,   nan,   nan,   nan,   nan],
       [  nan,   nan,   nan,   nan,   nan],
       [  nan,   nan,   nan,   nan,   nan]])

array([[  18.,   12.,  -10.,  -11.,  -18.],
       [ -55.,   49.,  -27.,   -9.,  -57.],
       [ -13.,   36.,   13.,  -79.,   72.],
       [  -3.,    5.,  -26.,   15.,  -88.],
       [  -1.,  -18., -100.,   68.,  -31.],
       [  17.,  -15.,  -78.,   41.,   55.]])

{'muchas perdidas': array([[False, False, False, False, False],
        [ True, False, False, False,  True],
        [False, False, False,  True, False],
        [False, False, False, False,  True],
        [False, False,  True, False, False],
        [False, False,  True, False, False]]),
 'perdidas': array([[False, False,  True,  True,  True],
        [False, False,  True,  True, False],
        [ True, False, False, False, False],
        [ True, False,  True, False, False],
        [False,  True, False, False,  True],
        [False,  True, False, False, False]]),
 'cero': array([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]),
 'ganancias': array([[ True,  True, False, False, False],
        [False, False, False, False, False],
        [False, False,  True, False, False

#### Hagamos Ahora el Indexing propuesto

array([[ 18.],
       [-55.],
       [-13.],
       [ -3.],
       [ -1.]])